apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-nfs-pv1
  labels:
    app: clustercontrol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.55.141
    path: "/storage/pods/cc/datadir"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-nfs-pv2
  labels:
    app: clustercontrol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  nfs:
    server: 192.168.55.141
    path: "/storage/pods/cc/cmon.d"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-nfs-pv3
  labels:
    app: clustercontrol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  nfs:
    server: 192.168.55.141
    path: "/storage/pods/cc/ssh"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-nfs-pv4
  labels:
    app: clustercontrol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.55.141
    path: "/storage/pods/cc/backups"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-cc-nfs-pv1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmond-cc-nfs-pv2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssh-cc-nfs-pv3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backups-cc-nfs-pv4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
